name: Nightly site build
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build site
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m src.main --stage all --out-json reports/latest.json --out-html reports/site/index.html --out-csv reports/latest.csv --limit 120 --max-pages 12 --timeout 25 --workers 6 --rate-limit 300
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

